### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by swang423** [lmaxwell/gmmVoiceConversion#2]
Hi, I like the idea of providing a self-contained package without installing too many other things. May I point out that the user does need to
1) Compile SPTK if it is not installed in their default location
2) provide mcep features, not the wav of both source and target speaker.

Is that correct? If so, could you also provide your parameters and commands for extracting the speech features? Thanks.

**Comment by lmaxwell** [comment]
please refer to  issue #1

**Comment by swang423** [comment]
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
